source: doc
destination: ..\gh-pages
timezone: America/Vancouver

baseurl: /SpaceBattleArena
url: http://mikeware.github.io/SpaceBattleArena

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
