source: doc
destination: ..\gh-pages
timezone: America/Vancouver

url: http://mikeware.github.io/SpaceBattleArena/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
